name: Deploy Frontend to Cloudflare

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: './react'
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build  # build your project

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
